name: Email Step Action

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: 23f1000257@ds.study.iitm.ac.in
        run: echo "This step is labeled with an email address!"
